### PR TITLE
Support for TypeScript 1.6.3.

### PR DESCRIPTION
**Pull request by jkonecki**

### CODE REVIEW

**Comment by Ky7m** [comment]
Thank you so much for your contribution! 
I'm reviewing and it will be merged as soon as possible (I use this package in production).
I saw some changes related to default localization in files and I'd prefer to use English localization as default.

**Comment by jkonecki** [comment]
Igor, I just copied the 1.6.3. files from my install. Feel free to modify
the PR as needed.

I can report that the package works on Visual Studio Online hosted agent.

**Comment by Ky7m** [comment]
Merged, thank you!

**Comment by jkonecki** [comment]
Hi, when do you think you will push the new NuGet package out?

**Comment by Ky7m** [comment]
Hi, please check a new version 1.6.4 of Nuget package.

**Pull request merged**
